services:
  ###> doctrine/doctrine-bundle ###
  database:
    container_name: ${POSTGRES_CONTAINER_NAME:-nfe-database}
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    ports:
      - "${POSTGRES_PORT:-3200}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  data_minio:
###< doctrine/doctrine-bundle ###
